bases/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from bases.views import Home,Registrar,Listar
urlpatterns = [
    path('',Home.as_view(),name='home'),
    path('registrar/',Registrar.as_view(),name='registrar'),
    path('estado/',Listar.as_view(),name='estado'),
    
    path('login/',auth_views.LoginView.as_view(template_name='bases/login.html'),
        name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='bases/login.html'),
        name='logout'),        
]

taller/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('',include(('bases.urls','bases'), namespace='bases')),
    path('admin/', admin.site.urls),
]

bases/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models

class Servicio(models.Model):
    id_servicio = models.IntegerField(primary_key=True)
    desc_servicio = models.CharField(max_length=50)
    valor_servicio = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'servicio'

class Empleado(models.Model):
    id_empleado = models.IntegerField(primary_key=True)
    rut_empleado = models.IntegerField()
    dv_empleado = models.CharField(max_length=1)
    p_nombre_empleado = models.CharField(max_length=25)
    s_nombre_empleado = models.CharField(max_length=25)
    p_apellido_empleado = models.CharField(max_length=25)
    s_apellido_empleado = models.CharField(max_length=25)
    direccion_empleado = models.CharField(max_length=25)
    numeracion_empleado = models.CharField(max_length=6)
    depto_empleado = models.CharField(max_length=6, blank=True, null=True)
    fono_empleado = models.IntegerField()
    correo_empleado = models.CharField(max_length=25)
    nombre_usu_empleado = models.CharField(max_length=25)
    contrasena_empleado = models.CharField(max_length=25)
    id_comuna = models.IntegerField()
    id_taller = models.IntegerField()
    id_cargo = models.BooleanField()

    class Meta:
        managed = False
        db_table = 'empleado'        

class Reserva(models.Model):
    id_reserva = models.AutoField(primary_key=True)
    fecha_reserva = models.DateField()
    hora_reserva = models.DateField()
    id_cliente = models.IntegerField(blank=True, null=True)
    id_servicio = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'reserva'

class Reserva2(models.Model):
    id_reserva = models.IntegerField(primary_key=True)
    fecha_reserva = models.DateTimeField()
    nombre = models.CharField(max_length=25)
    apellido = models.CharField(max_length=25)
    marca = models.CharField(max_length=25)
    modelo = models.CharField(max_length=25)
    correo = models.CharField(max_length=40)
    servicio = models.CharField(max_length=25)
    especialista = models.CharField(max_length=25)

    class Meta:
        managed = False
        db_table = 'reserva2'

inv/models.py
from django.db import models

# Create your models here.

bases/forms.py
from django.forms import *
from .models import Reserva2,Empleado,Servicio


class Reservaform(ModelForm):
    class Meta:
        model=Reserva2
        fields= {'nombre','apellido','correo','fecha_reserva' ,'marca','modelo','servicio','especialista'}
        labels = { 'nombre': 'Nombre','apellido': 'Apellido','correo': 'Correo','fecha_reserva': 'Fecha' ,
        'marca': 'Marca','modelo': 'Modelo',
        'servicio': 'Servicio','especialista': 'Especialista'
        }
        widget={ 'fecha_reserva': DateTimeInput ,'nombre': TextInput,
        'apellido': TextInput,'marca': TextInput,'modelo': TextInput,'correo': TextInput,'servicio': TextInput,'especialista': TextInput,
        }

class EspecialistaForm(ModelForm):
     class Meta:
         model=Empleado
         fields= ['p_nombre_empleado']


#class Reservaform2(ModelForm):
 #       form_classes = {
  #      'reserva': Reservaform2,
  #      'empleado': EspecialistaForm,
  #  }

bases/views.py
from django.shortcuts import render,redirect
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import models
from .models import Servicio, Empleado, Reserva2
from django.urls import reverse_lazy
from django import forms

from bases.forms import Reservaform

from django.contrib import messages 
from django.contrib.messages.views import SuccessMessageMixin 

from django.http import HttpResponseRedirect


class Home(LoginRequiredMixin, generic.TemplateView):
    template_name = 'bases/home.html'
    login_url='bases:login'


    def get_context_data(self, *args, **kwargs):
            reserva = Reserva2.objects.all()
            servicio = Servicio.objects.all()
            empleado = Empleado.objects.all()
            return {'objresv': reserva,'objserv': servicio, 'objempl': empleado}


class Registrar(LoginRequiredMixin,generic.CreateView):
    template_name = 'bases/listo.html'
    login_url='bases:login'
    model = Reserva2
    form_class = Reservaform
    success_message = 'Reserva Creada Correctamente !'
    success_url = reverse_lazy('bases:home')

class Listar(LoginRequiredMixin,generic.TemplateView):
    template_name = 'bases/listar.html'
    login_url='bases:login'

    def get_context_data(self, *args, **kwargs):
            reserva = Reserva2.objects.all()
            servicio = Servicio.objects.all()
            empleado = Empleado.objects.all()
            return {'objresv': reserva,'objserv': servicio, 'objempl': empleado}

inv/views.py
from django.shortcuts import render

# Create your views here.

bases/templates/bases/gracias.html
{% extends 'base/base.html' %}

{% block side_bar %}{% endblock %}

{% block page_content %}{% endblock %}
{% block footer %}{% endblock %}

bases/templates/bases/home.html
{% extends 'base/base.html' %}

{% block side_bar %}{% endblock %}

{% block page_content %}{% endblock %}



{% block registrar %}


<div class="container">

    <div class="card o-hidden border-0 shadow-lg my-5">
      <div class="card-body p-0">

        <div class="row">
          <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
          <div class="col-lg-7">
            <div class="p-5">
              <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">Solicitar Hora</h1>
              </div>
              <form method="POSt" class="user" enctype="multipart/form-data">
                {% csrf_token %}
                

  
                <div class="form-group row">
                  <!--
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    <input type="text" class="form-control form-control" name="nombre" id="id_nombre" placeholder="Nombre">
                  </div>
                  <div class="col-sm-6">
                    <input type="text" class="form-control form-control" name="apellido" id="id_apellido" placeholder="Apellido">
                  </div>
                </div>
                <div class="form-group">
                  <input type="email" class="form-control form-control" name="correo" id="id_correo" placeholder="Correo">
                </div>
                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    <input type="text" class="form-control form-control" name="marca" id="id_marca" placeholder="Marca">
                  </div>
                  <div class="col-sm-6">
                    <input type="text" class="form-control form-control" name="modelo" id="id_modelo" placeholder="Modelo">
                  </div>
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    <label for="daytime"></label>
                    <input type="datetime-local" class="form-control" name="fecha_reserva" id="id_fecha_reserva" name="daytime">
                  </div> -->
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    <label for="servicio"></label>
                    <input list="desc_servicio" class="form-control" name="servicio" method="get" id="id_servicio" placeholder="Elije tu servicio:">
                    <datalist id="desc_servicio">
                        {% if not objserv %}
                        <option value="nada">
                        {% endif %}
                        {% for serv in objserv %}
                            <option value={{ serv.desc_servicio }} >
                        {% endfor %}

                    </datalist>
                  </div>
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    <label for="especialista"></label>
                    <input list="especialistas" class="form-control" name="especialista" id="id_especialista" placeholder="Elije el especialista:">
                    <datalist id="especialistas">
                        {% if not objempl %}
                        <option value="nada">
                        {% endif %}
                        {% for empl in objempl %}
                            <option value={{ empl.p_nombre_empleado }} >
                        {% endfor %}
                    </datalist>

                  

 
            
                   


                  </div>
                </div> 
                <input type="submit" value="Save" class="btn btn-primary btn-user btn-block">
                  
              </input>

              </form>















{% endblock registrar %}  

bases/templates/bases/listar.html
{% extends 'base/base.html' %}

{% block side_bar %}{% endblock %}

{% block page_content %}{% endblock %}


{% block listar %}

<div class="card o-hidden border-0 shadow-lg my-5">
<table  class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
    <h2>Solicitudes</h2>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Correo</th>
      <th>Marca</th>
      <th>Modelo</th>
      <th>Servicio</th>
      <th>Especialista</th>
    </tr>
   
        {% if not objresv %}
        <td>Sin Datos</td>
        {% endif %}
    {% for serv in objresv %}  
    <tr> 
      <td>{{ serv.nombre }}</td>
      <td>{{ serv.apellido }}</td>
      <td>{{ serv.correo }}</td>
      <td>{{ serv.marca }}</td>
      <td>{{ serv.modelo }}</td>
      <td>{{ serv.servicio }}</td>
      <td>{{ serv.especialista }}</td>
    </tr>
    {% endfor %}  
   
</table>


{% endblock listar %}  
{% block footer %}{% endblock %}

bases/templates/bases/listo.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}

{% block side_bar %}{% endblock %}

{% block page_content %}{% endblock %}
{% block footer %}{% endblock %}


{% block registrar2 %}


<div class="container">

    <div class="card o-hidden border-0 shadow-lg my-5">
      <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
          <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
          <div class="col-lg-7">
            <div class="p-5">
              <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">Solicitar Hora</h1>
              </div>
<form method="post" class="user" >
    
    {% csrf_token %}
    
                
    <div>
     
    

     {% for field in form.visible_fields %}
     <div class="form-group">
       <label for="{{ field.id_for_label }}">{{ field.label }}</label>
       {{ field|add_class:'form-control' }}
       {% for error in field.errors %}
         <span class="help-block">{{ error }}</span>
       {% endfor %}
     </div>
   {% endfor %}

     <button type="submit" class="btn btn-primary">Aceptar</button>
     <a href="./" type="submit" class="btn btn-primary">Cancelar</a>
   </div> 
   </form>

   
</div>
</div>
</div>
</div>
</div>

</div>


   {% endblock registrar2 %}  

bases/templates/bases/login.html
{% extends 'base/base.html' %}

{% block side_bar %}{% endblock %}
{% block top_bar %}{% endblock %}
{% block page_content %}{% endblock %}
{% block footer %}{% endblock %}

{% block login %}

<div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Bienvenido</h1>
                    <small class="text-danger">
                      {% if form.errors %}
                        {% for field in form %}
                            {% if field.errors %}
                              {% for error in field.errors %}
                                {{ error|escape }}
                              {% endfor %}
                            {% endif %}
                        {% endfor %}

                        {% if form.non_field_errors %}
                            {% for error in form.non_field_errors %}
                              {{ error|escape }}
                            {% endfor %}
                        {% endif %}
                        

                      {% endif %}
                    </small>
                  </div>
                 <form class="user" method="POST">
                     {% csrf_token %}
                    <div class="form-group">
                      <input type="text" class="form-control form-control-user" id="id_username" name="username" aria-describedby="emailHelp" placeholder="Usuario">
                    </div>
                    <div class="form-group">
                      <input type="password" class="form-control form-control-user" id="id_password" name="password" placeholder="Password">
                    </div> 
                    <button type="submit" class="btn btn-primary btn-user btn-block">Acceder</button>
                    
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

  {% endblock %}

bases/templates/bases/registrar.html
{% extends 'base/base.html' %}

{% block side_bar %}{% endblock %}

{% block page_content %}{% endblock %}
{% block footer %}{% endblock %}


{% block registrar %}


<div class="container">

    <div class="card o-hidden border-0 shadow-lg my-5">
      <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
          <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
          <div class="col-lg-7">
            <div class="p-5">
              <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">Solicitar Hora</h1>
              </div>
              <form class="user" action="POST">
                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    <input type="text" class="form-control form-control-user" id="exampleFirstName" placeholder="Nombre">
                  </div>
                  <div class="col-sm-6">
                    <input type="text" class="form-control form-control-user" id="exampleLastName" placeholder="Apellido">
                  </div>
                </div>
                <div class="form-group">
                  <input type="email" class="form-control form-control-user" id="exampleInputEmail" placeholder="Correo">
                </div>
                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    <input type="text" class="form-control form-control-user" id="marca" placeholder="Marca">
                  </div>
                  <div class="col-sm-6">
                    <input type="text" class="form-control form-control-user" id="modelo" placeholder="Modelo">
                  </div>
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    <label for="daytime"></label>
                    <input type="datetime-local" class="form-control" id="daytime" name="daytime">
                  </div>
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    <label for="servicio"></label>
                    <input list="desc_servicio" class="form-control" name="servicio" method="get" id="servicio" placeholder="Elije tu servicio:">
                    <datalist id="desc_servicio">
                        {% if not objserv %}
                        <option value="nada">
                        {% endif %}
                        {% for serv in objserv %}
                            <option value={{ serv.desc_servicio }} >
                        {% endfor %}

                    </datalist>
                  </div>
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    <label for="especialista"></label>
                    <input list="especialistas" class="form-control" name="especialista" id="especialista" placeholder="Elije el especialista:">
                    <datalist id="especialistas">
                        {% if not objempl %}
                        <option value="nada">
                        {% endif %}
                        {% for empl in objempl %}
                            <option value={{ empl.p_nombre_empleado }} >
                        {% endfor %}
                    </datalist>
                  </div>
                </div>
                <button href="{% url 'bases:gracias/' %}" class="btn btn-primary btn-user btn-block">
                  Solicitar
                </button>
               
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>



{% endblock registrar %}  